baseURL = "https://usetania.org/"
languageCode = "en-gb"
theme = "tania2020"
googleAnalytics = "UA-133765833-1"
DefaultContentLanguage = "en"
disqusShortname = "usetania"
disableLanguages = ["hu"]

[params]
  description = "Tania is a free and open source farm management software."
  images = ["docs/dashboard.PNG"]

  [params.facebook]
    appid = "2277471495873880"
  
  [params.image]
    url = "docs/dashboard.PNG"
    width = 800
    height = 600
  
  [params.logo]
    url = "img/Tania_Icon200.png"
    width = 200
    height = 200

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.highlight]
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = true
      style = "monokai"
      tabWidth = 2
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[languages]
  [languages.en]
    title = "Tania ・ Open Source Farm Management Sofware"

    [[languages.en.menu.main]]
      name = "Documentation"
      url = "docs/"
      weight = 10
    
    [[languages.en.menu.main]]
      name = "Roadmap"
      url = "roadmap/"
      weight = 20

    [[languages.en.menu.main]]
      name = "Blog"
      url = "blog/"
      weight = 30
    
    [[languages.en.menu.gettingstarted]]
      name = "Overview"
      url = "docs/"
      weight = 10
    
    [[languages.en.menu.gettingstarted]]
      name = "Installation"
      url = "docs/installation/"
      weight = 20
    
    [[languages.en.menu.gettingstarted]]
      name = "Getting Help"
      url = "docs/getting-help/"
      weight = 30
    
    [[languages.en.menu.usingtania]]
      name = "Initial setup"
      url = "docs/initial-setup/"
      weight = 5

    [[languages.en.menu.usingtania]]
      name = "Dashboard"
      url = "docs/dashboard/"
      weight = 10
    
    [[languages.en.menu.usingtania]]
      name = "Area"
      url = "docs/area/"
      weight = 20
    
    [[languages.en.menu.usingtania]]
      name = "Crop"
      url = "docs/crop/"
      weight = 30
    
    [[languages.en.menu.usingtania]]
      name = "Reservoir"
      url = "docs/reservoir/"
      weight = 40
    
    [[languages.en.menu.usingtania]]
      name = "Inventory"
      url = "docs/inventory/"
      weight = 7
    
    [[languages.en.menu.usingtania]]
      name = "Settings"
      url = "docs/settings/"
      weight = 60
    
    [[languages.en.menu.roadmap]]
      name = "v2.0"
      url = "roadmap/"
      weight = 5

    [[languages.en.menu.roadmap]]
      name = "v1.5"
      url = "roadmap/v15"
      weight = 10
  
  [languages.id]
    title = "Tania | Sistem Manajemen Kebun Dengan Sumber Terbuka"

    [[languages.id.menu.main]]
      name = "Tentang"
      url = "about/"
      weight = 5

    [[languages.id.menu.main]]
      name = "Dokumentasi"
      url = "docs/"
      weight = 10
    
    [[languages.id.menu.main]]
      name = "Peta Jalan"
      url = "roadmap/"
      weight = 20

    [[languages.id.menu.main]]
      name = "Blog"
      url = "blog/"
      weight = 30
    
    [[languages.id.menu.main]]
      name = "Toko"
      url = "https://teespring.com/stores/usetania"
      weight = 40
    
    [[languages.id.menu.main]]
      name = "Kontak"
      url = "contact/"
      weight = 45
    
    [[languages.id.menu.gettingstarted]]
      name = "Seputar Tania"
      url = "docs/"
      weight = 10
    
    [[languages.id.menu.gettingstarted]]
      name = "Instalasi"
      url = "docs/installation/"
      weight = 20
    
    [[languages.id.menu.gettingstarted]]
      name = "Dapatkan Bantuan"
      url = "docs/getting-help/"
      weight = 30
    
    [[languages.id.menu.usingtania]]
      name = "Pengaturan Awal"
      url = "docs/initial-setup/"
      weight = 5

    [[languages.id.menu.usingtania]]
      name = "Dashboard"
      url = "docs/dashboard/"
      weight = 10
    
    [[languages.id.menu.usingtania]]
      name = "Area"
      url = "docs/area/"
      weight = 20
    
    [[languages.id.menu.usingtania]]
      name = "Crop"
      url = "docs/crop/"
      weight = 30
    
    [[languages.id.menu.usingtania]]
      name = "Reservoir"
      url = "docs/reservoir/"
      weight = 40
    
    [[languages.id.menu.usingtania]]
      name = "Inventory"
      url = "docs/inventory/"
      weight = 7
    
    [[languages.id.menu.usingtania]]
      name = "Settings"
      url = "docs/settings/"
      weight = 60
    
    [[languages.id.menu.roadmap]]
      name = "v2.0"
      url = "roadmap/"
      weight = 5

    [[languages.id.menu.roadmap]]
      name = "v1.5"
      url = "roadmap/v15"
      weight = 10

  [languages.el]
    title = "Tania | Λογισμικό Ανοιχτου Κώδικα Διαχείρισης Aγροκτήματος"
    languageName = "Greek"
    weight = 4

    [[languages.el.menu.main]]
      name = "Σχετικα"
      url = "about/"
      weight = 5

    [[languages.el.menu.main]]
      name = "Τεκμηριωση"
      url = "docs/"
      weight = 10
    
    [[languages.el.menu.main]]
      name = "Χαρτης"
      url = "roadmap/"
      weight = 20

    [[languages.el.menu.main]]
      name = "Blog"
      url = "blog/"
      weight = 30
    
    [[languages.el.menu.main]]
      name = "Καταστημα"
      url = "shop/"
      weight = 40
    
    [[languages.el.menu.main]]
      name = "Επικοινωνια"
      url = "contact/"
      weight = 45
    
    [[languages.el.menu.gettingstarted]]
      name = "Επισκόπηση"
      url = "docs/"
      weight = 10
    
    [[languages.el.menu.gettingstarted]]
      name = "Εγκατάσταση"
      url = "docs/installation/"
      weight = 20
    
    [[languages.el.menu.gettingstarted]]
      name = "Λήψη Βοήθειας"
      url = "docs/getting-help/"
      weight = 30
    
    [[languages.el.menu.usingtania]]
      name = "Αρχική Παραμετροποίηση"
      url = "docs/initial-setup/"
      weight = 5

    [[languages.el.menu.usingtania]]
      name = "Κεντρικός Πίνακας"
      url = "docs/dashboard/"
      weight = 10
    
    [[languages.el.menu.usingtania]]
      name = "Περιοχή"
      url = "docs/area/"
      weight = 20
    
    [[languages.el.menu.usingtania]]
      name = "Σοδειά"
      url = "docs/crop/"
      weight = 30
    
    [[languages.el.menu.usingtania]]
      name = "Ταμιευτήρας"
      url = "docs/reservoir/"
      weight = 40
    
    [[languages.el.menu.usingtania]]
      name = "Απόθεμα"
      url = "docs/inventory/"
      weight = 7
    
    [[languages.el.menu.usingtania]]
      name = "Ρυθμίσεις"
      url = "docs/settings/"
      weight = 60
    
    [[languages.el.menu.roadmap]]
      name = "v2.0"
      url = "roadmap/"
      weight = 5

    [[languages.el.menu.roadmap]]
      name = "v1.5"
      url = "roadmap/v15"
      weight = 10

  [languages.hu]
    title = "Tania | Open Source Farm Management Sofware"

    [[languages.hu.menu.main]]
      name = "Docs"
      url = "docs/"
      weight = 10
    
    [[languages.hu.menu.main]]
      name = "Roadmap"
      url = "roadmap/"
      weight = 20

    [[languages.hu.menu.main]]
      name = "Blog"
      url = "blog/"
      weight = 30
    
    [[languages.hu.menu.main]]
      name = "Shop"
      url = "https://teespring.com/stores/usetania"
      weight = 40
    
    [[languages.hu.menu.main]]
      name = "Contact Us"
      url = "contact/"
      weight = 45
    
    [[languages.hu.menu.gettingstarted]]
      name = "What is Tania?"
      url = "docs/"
      weight = 10
    
    [[languages.hu.menu.gettingstarted]]
      name = "Installation"
      url = "docs/installation/"
      weight = 20
    
    [[languages.hu.menu.gettingstarted]]
      name = "Getting Help"
      url = "docs/getting-help/"
      weight = 30
    
    [[languages.hu.menu.usingtania]]
      name = "Dashboard"
      url = "docs/dashboard/"
      weight = 10
    
    [[languages.hu.menu.usingtania]]
      name = "Area"
      url = "docs/area/"
      weight = 20
    
    [[languages.hu.menu.usingtania]]
      name = "Crop"
      url = "docs/crop/"
      weight = 30
    
    [[languages.hu.menu.usingtania]]
      name = "Reservoir"
      url = "docs/reservoir/"
      weight = 40
    
    [[languages.hu.menu.usingtania]]
      name = "Inventory"
      url = "docs/inventory/"
      weight = 50
    
    [[languages.hu.menu.usingtania]]
      name = "Settings"
      url = "docs/settings/"
      weight = 60
    
    [[languages.hu.menu.roadmap]]
      name = "2019"
      url = "roadmap/"
      weight = 10


